apiVersion: v1
kind: Service
metadata:
  name: hashgenerator-svc
  namespace: my-apps
spec:
  type: ClusterIP
  selector:
    app: hashgenerator
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3003